org: yeongyu
app: inssa-club
service: clubhouse-waitlist

frameworkVersion: "2"

provider:
    name: aws
    runtime: go1.x
    lambdaHashingVersion: 20201221
    stage: production
    apiGateway:
        minimumCompressionSize: 1024
    iamRoleStatements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource:
              - "arn:aws:s3:::clubhouse-waitlist"
    region: ap-northeast-1
    profile: lambda

package:
    exclude:
        - ./**
    include:
        - ./bin/**

functions:
    main:
        handler: bin/main
        events:
            - http:
                  path: /waitlist
                  method: post
            - http:
                  path: /waitlist
                  method: delete
        environment:
            IS_SERVERLESS: true
