definitions:
  forms.AddInterestRequestDocument:
    properties:
      clubhouse_user_id:
        example: 1234
        type: integer
      email:
        example: example@example.com
        type: string
    required:
    - email
    type: object
  forms.AddInterestResponseDocument:
    properties:
      clubhouse_user_id:
        example: 1234
        type: integer
      email:
        example: example@example.com
        type: string
      id:
        example: 0
        type: integer
    required:
    - email
    type: object
  forms.DeleteInterest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  forms.ErrorResponse:
    properties:
      detail:
        type: string
      error_type:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /interest:
    delete:
      consumes:
      - application/json
      description: Soft delete from interest list (= waitlist)
      parameters:
      - description: json body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/forms.DeleteInterest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/forms.ErrorResponse'
        "404":
          description: ""
      summary: Delete from interest list (= waitlist)
    post:
      consumes:
      - application/json
      description: add to interest list (= waitlist)
      parameters:
      - description: json body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/forms.AddInterestRequestDocument'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/forms.AddInterestResponseDocument'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/forms.ErrorResponse'
      summary: Add to interest list (= waitlist)
swagger: "2.0"
